# Generated by Django 6.0.5 on 2026-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_systemsharesettings_public_share_link_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsharesettings',
            name='timezone_name',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AlterField(
            model_name='admintodoitem',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('paused', 'Paused'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
