# Generated by Django 6.0.5 on 2026-05-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0014_systemsharesettings_timezone_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_received', to=settings.AUTH_USER_MODEL)),
                ('selected_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to='auth.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='drive_chatme_recipie_7df6df_idx'), models.Index(fields=['sender', 'recipient', 'created_at'], name='drive_chatme_sender__30a00e_idx')],
            },
        ),
    ]
