# Generated by Django 6.0.5 on 2026-05-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0015_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='selected_group',
        ),
    ]
