# Generated by Django 6.0.5 on 2026-05-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_remove_chatmessage_selected_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='drive_chatm_recipie_c6e4e4_idx',
            old_name='drive_chatme_recipie_7df6df_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='drive_chatm_sender__fc6791_idx',
            old_name='drive_chatme_sender__30a00e_idx',
        ),
    ]
