# Generated by Django 6.0.5 on 2026-05-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0017_rename_drive_chatme_recipie_7df6df_idx_drive_chatm_recipie_c6e4e4_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
