# Generated by Django 6.0.5 on 2026-05-08 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0018_delete_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('uploader_email', models.EmailField(max_length=320)),
                ('recipient_label', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_files_count', models.PositiveIntegerField(default=0)),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner__username', 'relative_path', 'uploader_email'],
            },
        ),
    ]
